STATE_MYFIELDS_SUMMARY = "myfields_summary"
STATE_FIELD_BINDING_METHOD = "field_binding_method"
STATE_FIELD_BINDING_LOCATION = "field_binding_location"
STATE_FIELD_BINDING_CODE = "field_binding_code"
STATE_FIELD_BINDING_CANDIDATE_SELECT = "field_binding_candidate_select"
STATE_FIELD_BINDING_CONFIRM = "field_binding_confirm"

FIELD_BINDING_STATES = {
    STATE_MYFIELDS_SUMMARY,
    STATE_FIELD_BINDING_METHOD,
    STATE_FIELD_BINDING_LOCATION,
    STATE_FIELD_BINDING_CODE,
    STATE_FIELD_BINDING_CANDIDATE_SELECT,
    STATE_FIELD_BINDING_CONFIRM,
}
