STATE_EVIDENCE_WAITING_LOCATION = "evidence_waiting_location"
STATE_EVIDENCE_WAITING_DOCUMENT = "evidence_waiting_document"
STATE_EVIDENCE_VALIDATING = "evidence_validating"

EVIDENCE_STATES = {
    STATE_EVIDENCE_WAITING_LOCATION,
    STATE_EVIDENCE_WAITING_DOCUMENT,
    STATE_EVIDENCE_VALIDATING,
}
