STATE_ONBOARDING_LANGUAGE_SELECT = "language_select"
STATE_ONBOARDING_NAME = "name_input"
STATE_ONBOARDING_PHONE = "phone_input"
STATE_ONBOARDING_CONFIRM = "project_confirm"
STATE_ONBOARDING_PENDING_APPROVAL = "pending_approval"

ONBOARDING_STATES = {
    STATE_ONBOARDING_LANGUAGE_SELECT,
    STATE_ONBOARDING_NAME,
    STATE_ONBOARDING_PHONE,
    STATE_ONBOARDING_CONFIRM,
    STATE_ONBOARDING_PENDING_APPROVAL,
}
